name = "upsale"
client_id = "d758557fe11ba3e2d67c0376240d16c8"
application_url = "https://upsale-cyan.vercel.app"
embedded = true

[access_scopes]
scopes = "write_orders,read_products,read_customers,read_analytics,write_discounts,read_discounts,read_cart_transforms,write_cart_transforms"

[auth]
redirect_urls = [
  "https://upsale-cyan.vercel.app/auth/callback",
  "https://upsale-cyan.vercel.app/standalone/callback"
]

[webhooks]
api_version = "2026-01"


[pos]
embedded = false
